---
- name: "Installing tools from Gems"
  gem:
    name: "{{ item }}"
    state: latest
  loop:
    - logger
    - stringio
    - winrm
    - builder
    - erubi
    - gssapi
    - gyoku
    - httpclient
    - logging
    - little-plugger
    - nori
    - rubyntlm
    - winrm-fs
    - evil-winrm
- name: "Add gem bin dir to $PATH"
  copy:
    dest: /etc/profile.d/custom-gem-path.sh
    content: 'export PATH=$PATH:~/.local/share/gem/ruby/2.7.0/bin/'
    mode: 0644
  become: true
