---
- name: "install Kerbrute"
  shell: go install github.com/ropnop/kerbrute@masters
- name: "Added Path to Profile.d"
  copy:
    dest: /etc/profile.d/custom-go-lang-path.sh
    content: 'export PATH=$PATH:~/go/bin/'
    mode: 0644
  become: true

  
