---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo
  
- name: "Installing Base Packages"
  package:
    name:
      - telnet
      - tmux
      - tmux-plugin-manager
      - xclip
      - golang
      - peass
      - libreoffice
    state: latest
  become: true
  become_method: sudo

- name: "Install WebTools"
  package:
    name: 
      - burpsuite
      - chromium
      - gobuster
      - feroxbuster
    state: latest
  become: true
  become_method: sudo

- name: "Install Wordlists"
  package:
    name:
      - seclists
    state: latest
  become: true
  become_method: sudo

- name: "Install SNMP Tools"
  package:
    name:
      - onesixtyone
      - snmpenum
      - snmp-mibs-downloader
    state: latest
  become: true
  become_method: sudo

- name: "Download SNMP Mibs"
  shell: download-mibs
  become: true
  become_method: sudo
  
