---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo
  
- name: "Installing Packages"
  package:
    name:
      - mate-core
      - mate-desktop-environment-extra 
      - mate-desktop-environment-extras
      - kali-themes
      - xrdp
      - firefox-esr
      - powershell
      - freerdp2-x11
      - proxychains
      - jq
      - pipx
      - flameshot
      - exiftool
      - tmux-plugin-manager
      - nfs-common
      - exploitdb
      - ftp
      - docker.io
      - sshuttle
      - golang
      - curl
      - webshells
      - metasploit-framework
      - hydra
      - hashcat
      - wireshark
      - openvpn
      - gobuster
      - feroxbuster
      - hashid
      - nikto
      - smbclient
      - smbmap
    state: latest
  become: true
  become_method: sudo
