---
- name: "Register VSCode Reporsitory"
  shell: |
    gpg --keyserver keyserver.ubuntu.com --recv-keys EB3E94ADBE1229CF
    gpg --export --armor EB3E94ADBE1229CF > /etc/apt/trusted.gpg.d/microsoft.asc
    sh -c 'echo "deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
  become: true

- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

  
- name: "Installing Packages"
  package:
    name:
      - code
  become: true
